### ISSUE TITLE
COLOR_FormatYUV420SemiPlanar throws MediaCodec$CodecException: Error 0x80001001

### ISSUE THREAD

**Issue by guichazan** [dbof10/Bitmp4#1]
Hi,

I am since yesterday trying to make your great library work. However, it shows the error on title. If i change to COLOR_FormatSurface, it throws IllegalStateException in native_dequeueOutputBuffer.

I'm testing in an old ZTE device with Android 5.0. Which device did you test this library?

Do you have any clues on how to fix this?

thanks

    guich

**Comment by dbof10** [comment]
Can you provide more information? Can you try it on another Lollipop device? you can try the sample app, it works on emulator.

**Comment by dbof10** [comment]
after some research, your device may not have correct encoder
