### ISSUE TITLE
Unable to play video that created from Sample app

### ISSUE THREAD

**Issue by JVeverGiveUp** [dbof10/Bitmp4#5]
I tried to import Sample App and run. When I click Export, the data generated (10MB and length of video is 0:00) could not open with any video player. Using Huewei Y 9 2018, Android 9

**Comment by dbof10** [comment]
I don't support custom rom devices like huawei, xiaomi etc

**Comment by JVeverGiveUp** [comment]
Hello dbof10, so which device I can test your Sample app

**Comment by dbof10** [comment]
you can try with google emulator
