### ISSUE TITLE
setFrameDelay(int) has no effect on the final result

### ISSUE THREAD

**Issue by Cheesetouched** [dbof10/Bitmp4#6]
No matter what you ms value you pass as a frame delay, it has no effect on the final result. Upon close inspection, I noticed that the frame delay value isn't being used anywhere during the encoding process. It'll be great to get some help here.

**Comment by Cheesetouched** [comment]
Could you show an example of how you would generate a video of 5 picture, with 1 second delay before the next picture is shown? delay(500) is a bit vague and I am not sure how it'll work.

**Comment by dbof10** [comment]
val bitmap = getBitmap()
delay(500) //delay 500ms
lib.addFrame(bitmap)
