### ISSUE TITLE
do you support different frame rates?

### ISSUE THREAD

**Issue by Lavr18** [dbof10/Bitmp4#7]
Hi,

Is it possible to use your software for different frame rates?
At the moment I can see it uses 20FPS as default. Is there a way to change it?

Thanks a lot,
Aliaksei

**Comment by dbof10** [comment]
you can try here 
https://github.com/dbof10/Bitmp4/blob/master/lib-bitmp4/src/main/java/com/ctech/bitmp4/MP4Encoder.java#L64

**Comment by Lavr18** [comment]
So looks like your are not providing any setters for that?
I'm reluctant to modify your code as I'm not an expert in video encoding...
